apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: alert-api-monitor
  namespace: monitoring  # Doit être le même namespace que Prometheus
  labels:
    release: prometheus  # Doit correspondre aux labels de ton déploiement Prometheus
spec:
  selector:
    matchLabels:
      app: alert-api  # Doit correspondre aux labels de ton service
  endpoints:
  - port: "5000"  # Nom ou numéro du port du service
    interval: 15s
    path: /metrics
