apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: custom-alert-rules
  namespace: monitoring  # Assure-toi que le namespace est correct
  labels:
    app: prometheus-operator
    release: prometheus  # Doit correspondre au label de ton déploiement Prometheus
spec:
  groups:
  - name: custom-alerts
    rules:
    - alert: CustomAlertTriggered
      expr: custom_alert == 1
      for: 1m  # L'alerte doit être déclenchée pendant 1 minute avant d'être envoyée
      labels:
        severity: critical
      annotations:
        summary: "Alerte personnalisée déclenchée"
        description: "L'API a déclenché une alerte personnalisée (custom_alert=1). Vérifiez l'API ou l'application concernée."
